import SessionProvider from '@/client/providers/next-auth-session';
import ReduxProvider from '@/client/providers/redux';
import Header from '@/components/pages/header';
import { session } from '@/server/auth';
import '@/styles/main.scss';
import { type Metadata } from 'next';
import { Inter } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Next-auth mongoDB - Home',
	description: 'Generated by create next app',
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const auth = await session();

	return (
		<html lang='en'>
			<body className={inter.className}>
				<ReduxProvider>
					<SessionProvider session={auth}>
						<Header />
						{children}
					</SessionProvider>
				</ReduxProvider>
			</body>
		</html>
	);
}
